# This is a basic workflow to help you get started with Actions

name: deploy to azure web app

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  BING_KEY : ${{ secrets.BING_KEY }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      #Set the BING API key from the github secrets into the code
      - name: Replace bing key
        run: |
          sed -i "s/{{BING_KEY}}/$BING_KEY/" ./public/index.html

      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
           python-version: 3.8
           
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/
      
      
  
  deploy-to-webapp:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: qiodemo
          publish-profile: ${{ secrets.DEPLOYMENT_PROFILE }}
